### ISSUE TITLE
Method `Last resort` sets `last_move_info` incorrectly

### ISSUE THREAD

**Issue by Lenart12** [gamescomputersplay/minesweeper-solver#10]
https://github.com/gamescomputersplay/minesweeper-solver/blob/a420b1377bbf530eb236f108531ad162a3ebbaad/minesweeper_solver.py#L716

Should be
```py
self.last_move_info = ("Last Resort", None, None)
```

**Comment by gamescomputersplay** [comment]
You are right. Fixed.
