### ISSUE TITLE
File not found 

### ISSUE THREAD

**Issue by Tszyau** [gamescomputersplay/minesweeper-solver#14]
when i tried to run the bot, it shows

FileNotFoundError: [Errno 2] No such file or directory: 'samples/msx-0.png'

when the files are here and the names are the same

**Comment by gamescomputersplay** [comment]
Hm... are you running it on Mac?

I actually haven't tested it on Mac. My best guess is that Mac requires explicit "./" to correctly work with relative paths.
I have added it. Let me know if it solves the problem.
